spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///edu_authority?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Kexin!00
  security:
    oauth2:
      jwt:
        signingKey: 123456

gate:
  ignore:
    authentication:
      startWith: /oauth,/open