server:
  port: 8090

spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YuanAaron/OnlineEdu
          username: xxx
          password: yyy
          default-label: master
          search-paths: config/OnlineEdu